version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database used by our app
    database: mydb
    schema: public
    tables:
      
      - name: jaffle_shop_orders
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time

      - name: jaffle_shop_customers

  - name: stripe
    tables:
      - name: payments